Massive homepage performance improvement
obsidiandynamics/kafdrop pull request #277
Opened 2021-05-16 19:31 UTC by jorkzijlstra

This refactoring makes it possible to load in my case 1600 topic with 11000 topic partition in 30 seconds (tested with a kafka stack is other side of the world which means a higher ttl) and consists of several changes. Main point is that this can be achieved by not going to kafka where needed, or combine several calls into one.

The changes consist of
1) Reuse the partitionInfoList which was already retrieved for the topicInfo and don't go to Kafka again for this.
2) Retrieve partitionSizes with only 2 calls in total instead of 2 calls per partition.
3) Don't get partition offsets on calls where its not needed .

One improvement maybe still to make is to change the `setAllPartitionSizes` and make it return the data. This is however called in 2 places which means setting the data again also needs to be called in 2 places.

2021-05-17 07:48 UTC, jorkzijlstra commented
I just now saw this one: https://github.com/obsidiandynamics/kafdrop/pull/142/files

I like this one over the split ot the getTopics method so Ill need to do some more changes

2021-05-25 18:16 UTC, jorkzijlstra commented
It would be nice if someone can review and give some comments so that I can hopefully finalize this and get it merged.

2022-01-28 18:30 UTC, davideicardi requested changes
For what I can understand it seems to be a very good improvement. Thank you!

I just have some concerns on the code style. For example can we rewrite function

```
synchronized void setAllPartitionSizes(Map<String, List<PartitionInfo>> topicsMap, List<TopicVO> topics)
```

to something like

```
synchronized Map<String, List<PartitionInfo>> getPartitionsSizes(List<TopicVO> topics)
```

I suspect that you have done some of the changes for performance reasons, but these kind of functions can be difficult to test and can have some strange side effects.

What do you think?

2022-01-28 20:51 UTC, jorkzijlstra commented
@davideicardi 

All these changes are basically just reducing the number of call to fetch kafka data or fetch less data.

It has been a while since I wrote this and I actually don't remember why I made it a side effecting function. Normally I never would have done that so I suspect I had a good reason at the time. That said I totally agree that is shouldn't have to be.


The offsets are only part the `TopicPartitionVO` which is part of the `TopicVO` and not of the `PartitionInfo`.
Aah so that is why I made it a side effecting functions. The TopicVO is the one that we inject and which needs updating. 
If I where to implement it now I would have written something like `synchronized List<TopicVO> topics withPartitionsSizes(List<TopicVO> topics)` where I would duplicate the topicVO and return the new one with the partitionSizes set.

The other option would I think be `synchronized Map<String, Map<Integer, TopicPartitionVO>> getPartitionsSizes(List<TopicVO> topics)` eg `Map<topicname, Map<partitionId, TopicPartitionVO>>`. This way we have all the identifiers (topicName and paritionId) which we need to set this data.

I'm curious what you think about which direction I should go.

2022-01-28 22:53 UTC, davideicardi commented
@jorkzijlstra

Consider that I'm not an expert on this project, I'm just trying to maintain it ;-), but from what I understand I your first solution. 
I just suggest to call the function `calculatePartitionsSizes` or something similar.
```
synchronized List<TopicVO> calculatePartitionsSizes(List<TopicVO> topics)
```

Also here some kind of unit test can be useful, but I agree that can be difficult ... consider it as a "nice to have"!

Thank you very much for you help and explanation!

2022-01-31 12:33 UTC, jorkzijlstra commented on src/main/java/kafdrop/model/TopicVO.java
> +import org.apache.kafka.common.PartitionInfo;
Should be removed, not used in here

2022-01-31 12:34 UTC, jorkzijlstra commented on src/main/java/kafdrop/service/KafkaHighLevelConsumer.java
> +  synchronized Map<String, List<PartitionInfo>> getAllTopic() {
Should be named getAllTopics

2022-01-31 16:05 UTC, jorkzijlstra commented
@davideicardi Thanks for starting to maintain it and the same as you I'm also not an expert on the project. 

I'm also not a Java programmer and don't know the programming standards for this particular project, which is why I was asking input which route I should take. 

I only did some cleanup yet but haven't had the time to change the method signature yet.

2022-01-31 19:37 UTC, jorkzijlstra commented
@davideicardi I have tried to go the route of returning a new TopicVO with the updated data. I did not finish writing the code because I felt it became way to ugly and it also requires a deepcopy of the TopicVO and all it partitionData.

I thought that copying the data and returning an updated version would be trivial to do. At least this is what I'm used to in Scala. However making a deepcopy in Java doesn't seem to be trivial at all. I would need to add a lot more code.

On the `/consumer/:id` route we are also fetching all topics, including offset and filtering down on topic where that group actually has any offsets available. By any means we are discarding almost all the data we are fetching from kafka, 

Taking this into account I feel that, with the current data model, I unfortunately don't see another option than to make it a side effecting function. So I left the method name as is, since it actually setting the partitionsizes. 

What are your thought about this?

2022-01-31 21:31 UTC, jorkzijlstra commented
@davideicardi 

I mentioned the consumer group issue previously and worked on that a bit and removed the getTopicsWithOffsets method again in this PR: https://github.com/jorkzijlstra/kafdrop/pull/1

2022-02-01 16:29 UTC, davideicardi approved these changes
LGTM!

Let's wait a couple of days to see if someone has any comment and then for me we can merge it.

2022-02-01 16:38 UTC, jorkzijlstra commented
I also just now merged https://github.com/jorkzijlstra/kafdrop/pull/1 since its also cleaning up a method.
As for testing I did see there are some placeholder tests created, but haven't yet looked into creating some.

2022-02-08 10:27 UTC, jorkzijlstra commented
I haven't had the chance to have a look into adding unit / integrations test. Despite this are you considering that the couple of days have passed already?

2022-02-08 10:44 UTC, merged

2022-02-08 13:22 UTC, jorkzijlstra commented
@davideicardi Many thanks for starting to maintain this repo.