Support Protobuf message format
obsidiandynamics/kafdrop pull request #62
Opened 2019-12-25 22:21 UTC by ctrongduc

Added support for topic with protobuf message type.

2020-01-03 19:47 UTC, ctrongduc commented
@ekoutanov I'd love to see this to be part of Kafdrop, please review the feature and let me know if anything need to be updated so this could be merged to main branch.

2020-01-03 19:54 UTC, ekoutanov commented
I'm away at the moment. I will probably take a look at it next week.
Meanwhile, there is still an outstanding LTGM issue I believe.

2020-01-03 19:57 UTC, ctrongduc commented
no worry, take your time. I believe the last commit addressed all LGTM issue, unless I read the report wrong, please do let me know if issue remains.

2020-01-05 23:15 UTC, ekoutanov requested changes
Thanks. Seems to work. I left a bunch of comments, if you could please take a look.

2020-01-05 23:15 UTC, ekoutanov commented on src/main/java/kafdrop/config/ProtobufDescriptorConfiguration.java
> +				LOG.error("No descriptor folder configured, skip the setting!!");
Is this really an error? Sounds more like an info. Errors should generally only be fatal events.

2020-01-05 23:15 UTC, ekoutanov commented on src/main/java/kafdrop/config/ProtobufDescriptorConfiguration.java
> +public class ProtobufDescriptorConfiguration {
Can we please apply standard formatting, if it's not too much trouble. The rest of the project uses two-space indents.

2020-01-05 23:15 UTC, ekoutanov commented on src/main/java/kafdrop/controller/MessageController.java
> +      	selectedFormat = MessageFormat.PROTOBUF;
Nit: spacing

2020-01-05 23:15 UTC, ekoutanov commented on src/main/java/kafdrop/util/ProtobufMessageDeserializer.java
> +		} catch (FileNotFoundException e) {
Should we try to propagate errors back to the caller so that we can show the error on the page?

2020-01-05 23:15 UTC, ekoutanov commented on README.md
> +Valid format values are `DEFAULT`, `AVRO`, `PROTOBUF`. This can also be configured at the topic level via dropdown when viewing messages.
Can we have a section in the README (or another .md file) that describes how to use the protobuf option?

2020-01-06 03:16 UTC, ctrongduc commented
Please review my latest commit, thanks!

2020-01-06 08:52 UTC, merged