searching messages in specific partition
obsidiandynamics/kafdrop pull request #678
Opened 2024-08-18 20:09 UTC by krejcp19

Hi team,
in my usecase I usually know in which partition I need to search data. This will help me to reduce message consumption from partition that surely doesn't contain messages I want to search.
Option to search across all parition is preserved.

2024-11-08 10:52 UTC, Bert-R requested changes
Thanks for this contribution and sorry for the long delay in responding.
The change looks good, except for some small formatting and spelling topics. See my comments.

2024-11-08 10:52 UTC, Bert-R commented on src/main/java/kafdrop/service/KafkaHighLevelConsumer.java
> +    if(partition != -1) {
```suggestion
    if (partition != -1) {
```

2024-11-08 10:52 UTC, Bert-R commented on src/main/java/kafdrop/service/KafkaHighLevelConsumer.java
> +      if(partitionOpt.isEmpty()) {
```suggestion
      if (partitionOpt.isEmpty()) {
```

2024-11-08 10:52 UTC, Bert-R commented on src/main/java/kafdrop/service/KafkaHighLevelConsumer.java
> +        throw new IllegalArgumentException("Partition does not exists in the topic");
```suggestion
        throw new IllegalArgumentException("Partition does not exist in topic");
```

2024-11-08 10:52 UTC, Bert-R commented on src/main/java/kafdrop/service/KafkaMonitorImpl.java
> +    final var records = highLevelConsumer.searchRecords(topic, searchString, partition, maxmuimCount, startTimestamp,
Since you are making a change here anyway, do you mind fixing the spelling error in `maximumCount` (now spelled as `maxmuimCount`)?

2024-11-25 19:55 UTC, krejcp19 commented
Hi, thank you for the review. All issues should be fixed.

2024-11-26 19:42 UTC, Bert-R approved these changes
Thanks a lot!

2024-11-26 19:45 UTC, merged